---
title: "Midterm 1"
output: pdf_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(stargazer)
library(psych)
library(mediation)
library(janitor)
library(haven)
library(tidyverse)

```

```{r, load data}

# Load Data

all_data <- read_dta("dataverse_files/replicationdata.dta") %>% clean_names()


```

# Abstract

This document is the culmination of the first half of the semester's studies in replicating published journal articles. In this document, I have replicated 

\newpage

```{r table 1, results='asis'}

noRelaxCond <- filter(all_data, anxcond3 > 0)

# Table 1 in paper
# (1)

m <- lm( data = noRelaxCond, formula = scd_brad_self_report1_mean ~ anxcond) 

# (2) 

y <- lm( data = noRelaxCond, immigration ~ storycond + anxcond + scd_brad_self_report1_mean) 
stargazer(m, y, header = FALSE)

```
\newpage

```{r, figure 2}

# figure 2


dta_small <- select(all_data, scd_brad_self_report1_mean, anxcond3) %>% filter(!is.na(anxcond3), !is.na(scd_brad_self_report1_mean))


ggplot(dta_small, aes(x = anxcond3, y = scd_brad_self_report1_mean)) + theme_minimal() +
  stat_summary(fun.y=mean, geom="point", size=2) + 
  stat_summary(fun.data = mean_se, geom = "errorbar")



```



\newpage



```{r, figure 3}
# figure 3

# Causal Mediation Plot

# Mediation Analysis
m.out<-mediate(m,y, sims=500, treat="anxcond", mediator="scd_brad_self_report1_mean", dropobs=TRUE, boot=TRUE, conf.level=.90)

plot(m.out, labels=c("ACME\n(Physiological \nReactivity)", "Direct Effect \n(Anxiety)", "Total Effect"), cex.axis = 0.6, title = "asd") 



```



```{r, extension}



```


